version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    environment:
      TAG: darklang/dark-classic-base
    steps:
      - checkout
      - run: echo "Building images for version $(./tag-version.sh)."
      - run: docker buildx build --target dark-classic-base -t $TAG:$(./tag-version.sh) .
      - deploy:
          name: Push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "${DOCKER_HUB_TOKEN}" | docker login --username stachudotnet --password-stdin
              docker push $TAG:$(./tag-version.sh)
            fi
